from flask import Flask, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

# Root endpoint for testing
@app.route('/', methods=['GET'])
def home():
    return jsonify({"message": "Flask server is running!"})

# Endpoint for llama JSON (accepts both GET and POST requests)
@app.route('/get-llama-json', methods=['GET', 'POST'])
def get_llama_json():
    llama_data = {
        "parentTitle": "Generated by Llama",
        "title": "Llama AI Output",
        "description": "This is the output generated from the Llama AI model."
    }
    return jsonify(llama_data)

if __name__ == '__main__':
    app.run(port=5002)

